config/routes.rb
Rails.application.routes.draw do

  root 'players#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :matches
  resources :players
  resources :users

end

app/models/player.rb
class Player < ActiveRecord::Base

  MAXIMUM_POINTS_DIFFRENCE = 0.06

  has_many :player_rating_changes

  scope :ordered_by_nicks, -> { order(:nickname) }
  scope :ordered_by_ranking, -> { order(rating_points: :desc) }

  belongs_to :user

  scope :top10, -> { Player.all }

  scope :only_active, -> (for_period_days: 30) do
    where(id: Match.where('created_at > :date', date: Date.today-for_period_days.days).map{|m| m.players.map(&:id)}.flatten)
  end

  belongs_to :created_by, class_name: 'User'

  after_create do
    unless created_by.players.exists?
      created_by.players << self
      created_by.save!
    end
  end

  def self.select_collection
    all.map{|p| [p.nickname, p.id] }
  end

  def matches
    Match.where('red_team_player_one_id = :myid OR red_team_player_two_id = :myid OR blue_team_player_one_id = :myid OR blue_team_player_two_id = :myid', myid: self.id)
  end

  def days_old
    (Date.today - self.created_at.to_date).to_i
  end

  def can_attach?
    self.user_id.blank?
  end

  def can_dettach?(user)
    self.user_id == user.id
  end

  def nickname
    if user_id.present?
      user.player_name
    else
      super
    end
  end

  # http://www.tropiceuro.com/rankings.php
  def rank(match)
    matches_limit = 10 #after this count of matches, we can assume accurate rating_points of player
    matches_count_limited = if self.matches.count < matches_limit then self.matches.count else matches_limit end
    matches_count_limited_total = match.players.map do |p|
      p.matches.count
    end
    matches_count_limited_total = matches_count_limited_total.map{|match_count| if match_count < matches_limit then match_count else matches_limit end}.inject(&:+)
    match_average_rating_points = match.players.map{|p| p.rating_points*(if p.matches.count < matches_limit then p.matches.count else matches_limit end)}.inject{|sum,x| sum + x }/matches_count_limited_total
    rating_points_old = self.rating_points
    rating_points_old + MAXIMUM_POINTS_DIFFRENCE *
        (match_average_rating_points - rating_points_old + match.success_value(self) *
            (1 - matches_count_limited / matches_count_limited_total )
        )
  end


end

app/controllers/api/v2/players_controller.rb
module Api::V2
  class PlayersController < ResourceController
    self.resource_class = Player
  end
end
#
#     before_action :set_player, only: [:show, :edit, :update, :destroy]
#
#   # GET /players
#   # GET /players.json
#   def index
#     @players = Player.ordered_by_ranking
#   end
#
#   # GET /players/1
#   # GET /players/1.json
#   def show
#     gon.player = @player.plot_data
#   end
#
#   # GET /players/new
#   def new
#     @player = Player.new
#   end
#
#   # GET /players/1/edit
#   def edit
#   end
#
#   # POST /players
#   # POST /players.json
#   def create
#     @player = Player.new(player_params.merge(created_by: current_user))
#
#     respond_to do |format|
#       if @player.save
#         format.html { redirect_to players_path, notice: 'Player was successfully created.' }
#         format.json { render :show, status: :created, location: @player }
#       else
#         format.html { render :new }
#         format.json { render json: @player.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   # PATCH/PUT /players/1
#   # PATCH/PUT /players/1.json
#   def update
#     respond_to do |format|
#       if @player.update(player_params)
#         format.html { redirect_to @player, notice: 'Player was successfully updated.' }
#         format.json { render :show, status: :ok, location: @player }
#       else
#         format.html { render :edit }
#         format.json { render json: @player.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   # DELETE /players/1
#   # DELETE /players/1.json
#   def destroy
#     @player.destroy
#     respond_to do |format|
#       format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end
#
#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_player
#       @player = Player.find(params[:id])
#     end
#
#     # Never trust parameters from the scary internet, only allow the white list through.
#     def player_params
#       params.require(:player).permit(:nickname, :user_id)
#     end
# end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.ordered_by_ranking
    if params['with_inactive'] != 'true' && !ENV['DEMO_MODE']
      @players = @players.only_active
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    gon.player = {id: @player.id}
    rating_changes = @player.player_rating_changes.sort {|a,b| a.match.confirmed_at <=> b.match.confirmed_at}
    gon.player[:dates] = rating_changes.map{ |rc| rc.match.confirmed_at }
    gon.player[:dates].unshift(@player.created_at)
    gon.player[:dates].map! { |d|  d.strftime('%Y-%m-%d %H:%M') }
    score = 1500
    gon.player[:scores] = rating_changes.map(&:rating_points_difference).map do |rpd|
      score += rpd
    end
    gon.player[:scores].unshift(1500)

    gon.player[:plot_data] = []

    gon.player[:dates].each_with_index do |d, i|
      gon.player[:plot_data].push({date: d, score: gon.player[:scores][i]})
    end
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params.merge(created_by: current_user))

    respond_to do |format|
      if @player.save
        format.html { redirect_to players_path, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      p = [:user_id]
      p.push(:nickname) if @player.user_id.try(:blank?) || @player.user_id == current_user.id
      params.require(:player).permit(*p)
    end
end

app/views/players/_form.html.slim
= form_for @player do |f|
  - if @player.errors.any?
    #error_explanation
      h2 = "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      ul
        - @player.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :nickname
    = f.text_field :nickname, class:"form-control", autofocus: 'autofocus'
  .actions = f.submit

app/views/players/_table.html.slim
table.table.table-responsive
  thead
    tr
      th = I18n.t('activerecord.attributes.player.rating_points')
      th = I18n.t('activerecord.attributes.player.nickname')
      th.hidden-xs = I18n.t('activerecord.attributes.user.email')
      - unless @table_without_actions
        th = I18n.t('activerecord.attributes.player.attach')
        th = I18n.t('activerecord.attributes.player.dettach')
  tbody
    - @players.each_with_index do |player, i|
      tr
        td = player.rating_points
        td = link_to player.nickname, player_path(player)
        td.hidden-xs
          - if player.user.present?
            = link_to player.user.try(:email), user_path(player.user)
        - unless @table_without_actions
          td
            - if player.can_attach?
              = link_to 'Attach!', {:action => "update", :controller => "players",
                      :id =>player.id, player: {user_id: current_user.id}}, method: :put
          td
            - if player.can_dettach?(current_user)
              = link_to 'Dettach!', {:action => "update", :controller => "players",
                      :id =>player.id, player: {user_id: nil}}, method: :put
  - unless @table_without_actions
    tfoot
      tr
        th AVG:
        th
        th.hidden-xs
        - unless @table_without_actions
          th
          th
      tr
        td = Player.all.sum(:rating_points)/Player.all.count
        td
        td.hidden-xs
        - unless @table_without_actions
          td
          td

app/views/players/edit.html.slim
.container-fluid
  h1 Editing player

  == render 'form'

  = link_to 'Show', @player
  '|
  = link_to 'Back', players_path

app/views/players/index.html.slim
.container-fluid
  .row: col-md-12
    h3 Listing players
    = link_to I18n.t('links.player.new'), new_player_path, class: 'btn'
    = link_to I18n.t('links.match.new'), new_match_path, class: 'btn'
    .btn.btn-default.hidden-xs
      - if params['with_inactive'] == 'true'
        = link_to 'Active players', players_path
      - else
        = link_to 'Inactive players', players_path(params: { with_inactive: true })
    == render 'players/table'

app/views/players/new.html.slim
.container-fluid
  h1 New player
  == render 'form'
  = link_to 'Back', players_path

app/views/players/show.html.slim
.container-fluid

  p
    strong Nickname:
    = @player.nickname
  p
    strong rating_points points:
    = @player.rating_points

  #player_rating_plot

  = link_to 'Edit', edit_player_path(@player)
  '|
  = link_to 'Back', players_path

javascript:
  var formatDate = d3.time.format("%Y-%m-%d %H:%M");
  var parseDate = d3.time.format("%Y-%m-%d %H:%M:%S").parse;

  var data = gon.player.plot_data

  data.forEach(function(item){
    item.date = formatDate.parse(item.date);
  });

  var margin = {top: 20, right: 20, bottom: 30, left: 50};
  var width = ($(window).width()*0.9) - margin.left - margin.right;
  var height = 500 - margin.top - margin.bottom;

  var x = d3.time.scale().range([0, width]);

  var y = d3.scale.linear()
      .range([height, 0]);

  var xAxis = d3.svg.axis()
      .scale(x)
      .orient("bottom")
      .tickFormat(d3.time.format("%m-%d"));

  var yAxis = d3.svg.axis()
      .scale(y)
      .orient("left");

  var line = d3.svg.line()
      .interpolate("basis")
      .x(function(d) { return x(d.date); })
      .y(function(d) { return y(d.score); });

  var svg = d3.select("#player_rating_plot").append("svg")
      .attr("width", width + margin.left + margin.right)
      .attr("height", height + margin.top + margin.bottom)
    .append("g")
      .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  x.domain(d3.extent(data, function(d) { return d.date; }));
  y.domain(d3.extent(data, function(d) { return d.score; }));

  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis);

  svg.append("g")
      .attr("class", "y axis")
      .call(yAxis)
    .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Rating points");

  svg.append("path")
      .datum(data)
      .attr("class", "line")
      .attr("d", line);

coffee:
  $(document).on 'page:before-change', ->
    d3.select("svg").remove()