config/routes.rb
Rails.application.routes.draw do

  root 'players#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :matches
  resources :players
  resources :users

end

app/models/match.rb
class Match < ActiveRecord::Base

  default_scope { order(created_at: :desc) }

  belongs_to :red_team_player_one,  class_name: 'Player'
  belongs_to :red_team_player_two,  class_name: 'Player'
  belongs_to :blue_team_player_one, class_name: 'Player'
  belongs_to :blue_team_player_two, class_name: 'Player'

  has_many :player_rating_changes

  belongs_to :created_by,   class_name: 'User'
  belongs_to :confirmed_by, class_name: 'User'

  validates :date, :created_by_id, presence: true
  validates :confirmed_at, presence: true, if: 'confirmed_by_id.present?'
  validates_inclusion_of :already_ranked, in: [true, false]

  before_validation do
    if confirmed_by_id_changed?
      self.confirmed_at = DateTime.now
    end
  end

  before_save do
    !self.already_ranked
  end

  validate do
    errors.add :confirmed_by if self.confirmed_by.present? && !self.can_be_confirmed?(self.confirmed_by)
  end

  validate do
    if red_team_score > blue_team_score
      errors.add :red_team_score if red_team_score < 3
    else
      errors.add :blue_team_score if blue_team_score < 3
    end
  end

  validate do
    if self.can_be_ranked? && red_team_score.to_i == blue_team_score.to_i
      errors.add :red_team_score, "Score can't be even"
      errors.add :blue_team_score, "Score can't be even"
    end
  end

  validate do
    errors.add :base if self.already_ranked
  end

  validate do
    if self.can_be_ranked? && (arr = players.flatten.map(&:id).uniq).size < 4
      errors.add :players, "Match should have some players instead it has #{arr.size}"
    end
  end

  validate do
    unless players.present?
      errors.add :players, "Match should have at least some players instead it has #{players.size}"
    end
  end

  validates :blue_team_score, numericality: { only_integer: true, less_than_or_equal_to: 3, greater_than_or_equal_to: 0}, presence: true
  validates :red_team_score, numericality: { only_integer: true, less_than_or_equal_to: 3, greater_than_or_equal_to: 0}, presence: true

  after_commit do
    match = self
    Rails.application.scheduler.in '3s' do
      puts "Reranking players in scheduler"
      match.rerank_players
    end
  end

  def players
    [red_team_players, blue_team_players].flatten
  end

  def red_team_players
    [red_team_player_one, red_team_player_two]
  end

  def blue_team_players
    [blue_team_player_one, blue_team_player_two]
  end

  def can_be_ranked?
    is_confirmed?
  end

  def is_confirmed?
    self.confirmed_by_id.present? && self.created_by_id.present?
  end

  def created_by_team
    if (self.created_by.players.to_a & self.blue_team_players).size > 0
      :blue
    elsif (self.created_by.players.to_a & self.red_team_players).size > 0
      :red
    else
      :none
    end
  end

  def can_confirm_players
    if created_by_team == :red
      self.blue_team_players
    elsif created_by_team == :blue
      self.red_team_players
    else
      self.players
    end
  end

  def can_be_confirmed?(user)
    return false if self.is_confirmed? && !confirmed_by_id_changed?
    user.present? && user.players.where(id: can_confirm_players.map(&:id)).exists?
  end

  def winners
    if self.winner_team_color == :red
      red_team_players
    else
      blue_team_players
    end
  end

  def winner_team_color
    if red_team_score > blue_team_score
      :red
    else
      :blue
    end
  end

  def success_value(player)
    success_multipler = if self.winners.include?(player)
      if self.winner_team_color == :red
        red_team_score - blue_team_score
      else
        blue_team_score - red_team_score
      end
    else # looser
      if self.winner_team_color == :red
        blue_team_score - red_team_score
      else
        red_team_score - blue_team_score
      end
    end

    if self.winners.include?(player)
      350 + (50*success_multipler)
    else
      -350 + (50*success_multipler)
    end
  end

  def red_team_players_nicknames
    red_team_players.map &:nickname
  end

  def blue_team_players_nicknames
    blue_team_players.map &:nickname
  end

  def rating_points_difference_for(player)
    self.player_rating_changes.find_by(player_id: player.id).try(:formatted_rating_points_difference)
  end

  def self.rerank_players
    puts "Reranking all matches at: #{Time.now}"
    ActiveRecord::Base.transaction do
      Player.all.update_all({rating_points: 1500})
      PlayerRatingChange.destroy_all
      Match.where.not(confirmed_by_id: nil).to_a.sort_by(&:confirmed_at).each do |match|
        match.rerank_players
      end
    end
  end

  def rerank_players
    if self.can_be_ranked? && !self.already_ranked
      self.reload

      #nie można zmieniać rating_pointsów podczas pracy algorytmu rankujacego wiec
      # zapisujemy nowe rating_pointsy a potem przypisujemy je playerom
      new_rating_points = self.players.flatten.map{|p| {id: p.id, rating_points: p.rank(self)} }
      new_rating_points.each do |hash|
        player_id = hash[:id].to_i
        player = Player.find(player_id)
        prc = PlayerRatingChange.find_or_initialize_by(player_id: player_id, match_id: self.id)
        prc.rating_points_difference = hash[:rating_points] - player.rating_points
        player.rating_points = hash[:rating_points]
        player.save!
        prc.save!
      end
      self.update_attribute(:already_ranked, true)
    end
    true
  end

end

app/controllers/api/v2/matches_controller.rb
module Api::V2
  class MatchesController < ResourceController
    self.resource_class = Match

    def index
      super do
        @matches = @matches.order(:created_at)
        player_rating_changes = PlayerRatingChange.where(match: @matches)
        self.render_hash['player_rating_changes'] = player_rating_changes
        self.render_hash['players'] = Player.where(id: player_rating_changes.pluck(:player_id))
      end

    end
    private

    def match_params
      params[:match].permit(:red_team_score,
                            :blue_team_score,
                            :date,
                            :red_team_player_one_id,
                            :red_team_player_two_id,
                            :blue_team_player_one_id,
                            :blue_team_player_two_id,
                            :confirmed_by_id
      )
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.slim
= form_for @match do |f|
  - if @match.errors.any?
    #error_explanation
      h2 = "#{pluralize(@match.errors.count, "error")} prohibited this match from being saved:"
      ul
        - @match.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :date
    = f.date_field :date, class: "form-control", required: 'required', "data-provide" => "datepicker",
            "data-date-format"=>"yyyy-mm-dd", pattern:"^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$",
            title: "Data w formacie rrrr-mm-dd", value: Date.today
  /TODO: edycja będzie miała już ustawione wartości w selectach
  table.table.table-responsive
    colgroup
      col style="background-color:#c0392b;"
      col style="background-color:#2980b9;"
    thead
      tr
        th = I18n.t('activerecord.attributes.match.red_team')
        th = I18n.t('activerecord.attributes.match.blue_team')
    tbody
      tr
        td = f.collection_select(:red_team_player_one_id, Player.ordered_by_nicks, :id, :nickname, include_blank: true)
        td = f.collection_select(:blue_team_player_one_id, Player.ordered_by_nicks, :id, :nickname, include_blank: true)
      tr
        td = f.collection_select(:red_team_player_two_id, Player.ordered_by_nicks, :id, :nickname, include_blank: true)
        td = f.collection_select(:blue_team_player_two_id, Player.ordered_by_nicks, :id, :nickname, include_blank: true)
      tr
        td.form-group
          = f.number_field :red_team_score, class: 'form-control'
        td.form-group
          = f.number_field :blue_team_score, class: 'form-control'
  .actions = f.submit

app/views/matches/_table.html.slim
table.table.table-responsive
  thead
    tr
      th = I18n.t('activerecord.attributes.match.red_team_nicknames')
      th style="text-align: center;"
        = "#{I18n.t('activerecord.attributes.match.red_team_score')}:#{I18n.t('activerecord.attributes.match.blue_team_score')}"
      th = I18n.t('activerecord.attributes.match.blue_team_nicknames')
      th.hidden-xs = I18n.t('activerecord.attributes.match.ranked')
      th.hidden-xs = I18n.t('activerecord.attributes.match.confirm')

  tbody
    - @matches.each do |match|
      tr data-href=match_path(match)
        td style="color: #c0392b;"
          - match.red_team_players.each do |player|
            span = "#{player.nickname} #{match.rating_points_difference_for(player)}"
            br
        td style="text-align: center;"
          b style="color: #c0392b;" = match.red_team_score
          | :
          b style="color: #2980b9;" = match.blue_team_score
        td style="color: #2980b9;"
          - match.blue_team_players.each do |player|
            span = "#{player.nickname} #{match.rating_points_difference_for(player)}"
            br
        td.hidden-xs = match.can_be_ranked?
        td.hidden-xs
          - if match.can_be_confirmed?(current_user)
            = link_to 'Confirm!', { :action=>"update", :controller=>"matches",
                    :id=>match.id, match:{ confirmed_by_id: current_user.id } }, method: :put

app/views/matches/edit.html.slim
.container-fluid
  h1 Editing match

  == render 'form'

  = link_to 'Show', @match
  '|
  = link_to 'Back', matches_path

app/views/matches/index.html.slim
.container-fluid
  h1 Listing matches
  = link_to I18n.t('links.match.new'), new_match_path, class: 'btn'
  == render 'matches/table'

app/views/matches/new.html.slim
.container-fluid
  h1 New match

  == render 'form'

  = link_to 'Back', matches_path

app/views/matches/show.html.slim
.container-fluid
  p Date: #{@match.date}
  p Ranked?: #{@match.can_be_ranked?}
  table.table.table-responsive.table-bordered
    thead
      tr
        th style="background-color:#c0392b;" = I18n.t('activerecord.attributes.match.red_team')
        th style="background-color:#2980b9;" = I18n.t('activerecord.attributes.match.blue_team')
    tbody
      tr
        td = @match.red_team_player_one.nickname
        td = @match.blue_team_player_one.nickname
      tr
        td = @match.red_team_player_two.nickname
        td = @match.blue_team_player_two.nickname
      tr
        td = @match.red_team_score
        td = @match.blue_team_score
br
  - if @match.can_be_confirmed?(current_user)
    = link_to 'Confirm!', { :action=>"update", :controller=>"matches",
            :id=>@match.id, match:{ confirmed_by_id: 1 } }, method: :put
    '|
  = link_to 'Edit', edit_match_path(@match), class: 'btn'
  '|
  = link_to 'Back', matches_path, class: 'btn'