config/routes.rb
Rails.application.routes.draw do

  root 'players#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :matches
  resources :players
  resources :users

end

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse.border-radius-0
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-2" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class:"navbar-brand"
        .inline
          img src="/icon.png"
          .inline Foosball Open Ranking
    - if current_user.present?
      #bs-example-navbar-collapse-2.collapse.navbar-collapse
        ul.nav.navbar-nav
          li
            = link_to players_path
              span.glyphicon.glyphicon-user
              = I18n.t('links.player.index')
          li
            = link_to matches_path
              span.glyphicon.glyphicon-inbox
              = I18n.t('links.match.index')
          li
            = link_to new_match_path
              span.glyphicon.glyphicon-plus
              span.glyphicon.glyphicon-inbox
              = I18n.t('links.match.new')
        ul.nav.navbar-nav.navbar-right
          li
            a href="https://github.com/ipepe/foosball-open-ranking"
              span.glyphicon.glyphicon-tags
              | GitHub.com
          - if current_user.present?
            li
              = link_to destroy_user_session_path
                span.glyphicon.glyphicon-log-out
                = I18n.t('links.devise.logout') + ' ' + current_user.label
          - else
            li
              = link_to new_user_session_path
                span.glyphicon.glyphicon-log-in
                = I18n.t('links.devise.login')

app/views/layouts/application.html.slim
doctype html
html lang=I18n.locale
  head
    title = I18n.t('application.title')
    link(rel="shortcut icon" href="/icon.png")
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width"
    meta name="mobile-web-app-capable" content="yes"
    meta name="apple-mobile-web-app-capable" content="yes"
    meta charset="utf-8"
    == stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags


  body
    == include_gon
    /== render 'layouts/header'
    .container-fluid
      - if [notice,alert].any?(&:present?)
        .container
          - if alert.present?
            h4.alert.alert-danger.alert-dismissible role="alert"
              button.close aria-label="Close" data-dismiss="alert" type="button"
                span aria-hidden="true"  &times;
              = alert
          - if notice.present?
            h4.alert.alert-info.alert-dismissible role="alert"
              button.close aria-label="Close" data-dismiss="alert" type="button"
                span aria-hidden="true"  &times;
              = notice
      == yield